services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      NEXT_PUBLIC_API_URL: http://backend:8000
    volumes:
      - .:/app
    command: npm run dev
    networks:
      - app-network

  backend:
    build:
      context: ./python-service
    ports:
      - "8001:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

# No top-level volumes needed as DB is external (Supabase)