export const DATABASE_ID =  process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID!;
export const WORKSPACES_ID = process.env.NEXT_PUBLIC_APPWRITE_WORKSPACES_ID!;
export const ATTACHMENTS_BUCKET_ID = process.env.NEXT_PUBLIC_APPWRITE_ATTACHMENTS_BUCKET_ID!;
export const MEMBERS_ID = process.env.NEXT_PUBLIC_APPWRITE_MEMBERS_ID!;
export const PROJECTS_ID = process.env.NEXT_PUBLIC_APPWRITE_PROJECTS_ID!;
export const TASKS_ID = process.env.NEXT_PUBLIC_APPWRITE_TASKS_ID!;
export const COMMENTS_ID = process.env.NEXT_PUBLIC_APPWRITE_COMMENTS_ID!;
export const TASKLOGS_ID = process.env.NEXT_PUBLIC_APPWRITE_TASKLOGS_ID!;
export const TASK_ATTACHMENT_ID = process.env.NEXT_PUBLIC_APPWRITE_TASK_ATTACHMENT_ID!;
export const CHATS_ID = process.env.NEXT_PUBLIC_APPWRITE_CHATS_ID!;
export const MESSAGES_ID = process.env.NEXT_PUBLIC_APPWRITE_MESSAGES_ID!;
export const DOCUMENTS_ID = process.env.NEXT_PUBLIC_APPWRITE_DOCUMENTS_ID!;
export const SUGGESTIONS_ID = process.env.NEXT_PUBLIC_APPWRITE_SUGGESTIONS_ID!;

export const APPWRITE_ENDPOINT = process.env.NEXT_PUBLIC_APPWRITE_ENDPOINT!;
export const APPWRITE_PROJECT = process.env.NEXT_PUBLIC_APPWRITE_PROJECT!;